version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-container
    restart: always
    ports:
      - "8080:8080"
      - '50000:50000'
    volumes:
      - jenkins:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    environment:
      - "JENKINS_OPTS=--prefix=/jenkins"
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '822:22'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_log:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

volumes:
  gitlab_config:
  gitlab_log:
  gitlab_data:
  jenkins:
  jenkins_home: